branch-defaults:
  default:
    environment: spring-stg
    group_suffix: null
deploy:
  artifact: target/SpringWebApp.war
environment-defaults:
  profile-stg:
    branch: null
    repository: null
global:
  application_name: springservice
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Tomcat 8 with Java
    8 running on 64bit Amazon Linux/2.7.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
